apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emall-runtime-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: emall-platform-vault
  target:
    name: emall-runtime-secret
    creationPolicy: Owner
  data:
    - secretKey: EMALL_DB_USERNAME
      remoteRef:
        key: emall/runtime
        property: dbUsername
    - secretKey: EMALL_DB_PASSWORD
      remoteRef:
        key: emall/runtime
        property: dbPassword
    - secretKey: EMALL_MIGRATION_DB_USERNAME
      remoteRef:
        key: emall/migration
        property: dbUsername
    - secretKey: EMALL_MIGRATION_DB_PASSWORD
      remoteRef:
        key: emall/migration
        property: dbPassword
    - secretKey: EMALL_SHARDING_DATASOURCE_USERNAME
      remoteRef:
        key: emall/runtime
        property: dbUsername
    - secretKey: EMALL_SHARDING_DATASOURCE_PASSWORD
      remoteRef:
        key: emall/runtime
        property: dbPassword
    - secretKey: EMALL_FIELD_ENCRYPTION_KEY
      remoteRef:
        key: emall/runtime
        property: fieldEncryptionKey
    - secretKey: EMALL_INTERNAL_OPERATIONS_TOKEN
      remoteRef:
        key: emall/runtime
        property: internalOperationsToken
    - secretKey: EMALL_SECURITY_AUTH_TOKEN_SECRET
      remoteRef:
        key: emall/runtime
        property: authTokenSecret
    - secretKey: EMALL_PAYMENT_CALLBACK_SECRET
      remoteRef:
        key: emall/runtime
        property: paymentCallbackSecret
    - secretKey: EMALL_PAYMENT_CHANNEL_API_KEY
      remoteRef:
        key: emall/runtime
        property: paymentChannelApiKey
    - secretKey: EMALL_PAYMENT_CHANNEL_URL
      remoteRef:
        key: emall/runtime
        property: paymentChannelUrl
    - secretKey: EMALL_FLASH_SALE_TOKEN_SECRET
      remoteRef:
        key: emall/runtime
        property: flashSaleTokenSecret
