CREATE TABLE virtual_shard_placement (
    placement_id VARCHAR(80) NOT NULL,
    namespace VARCHAR(64) NOT NULL,
    virtual_shard INT NOT NULL,
    mapping_version BIGINT NOT NULL,
    epoch BIGINT NOT NULL,
    migration_id VARCHAR(36) NULL,
    state VARCHAR(32) NOT NULL,
    primary_placement_json TEXT NOT NULL,
    target_placement_json TEXT NULL,
    cutover_not_before TIMESTAMP(6) NULL,
    observation_until TIMESTAMP(6) NULL,
    copy_cursor VARCHAR(512) NULL,
    source_row_count BIGINT NULL,
    target_row_count BIGINT NULL,
    source_checksum VARCHAR(128) NULL,
    target_checksum VARCHAR(128) NULL,
    cdc_lag BIGINT NULL,
    cutover_completed BOOLEAN NOT NULL DEFAULT FALSE,
    operator_name VARCHAR(128) NOT NULL,
    failure_reason VARCHAR(512) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (placement_id),
    UNIQUE KEY uk_virtual_shard_coordinate (namespace, virtual_shard),
    KEY idx_virtual_shard_state (state, updated_at),
    KEY idx_virtual_shard_namespace (namespace, virtual_shard)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE virtual_shard_migration_audit (
    audit_id BIGINT NOT NULL AUTO_INCREMENT,
    placement_id VARCHAR(80) NOT NULL,
    migration_id VARCHAR(36) NULL,
    from_state VARCHAR(32) NULL,
    to_state VARCHAR(32) NOT NULL,
    previous_version BIGINT NOT NULL,
    new_version BIGINT NOT NULL,
    epoch BIGINT NOT NULL,
    operator_name VARCHAR(128) NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (audit_id),
    KEY idx_virtual_shard_audit_coordinate (placement_id, audit_id),
    KEY idx_virtual_shard_audit_migration (migration_id, audit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
