CREATE DATABASE IF NOT EXISTS emall_user CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_product CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_inventory CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_order CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_cart CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_payment CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_pricing CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_marketing CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_search CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_fulfillment CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_review CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_after_sales CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_merchant CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_flash_sale CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_recommendation CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_cost CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_identity CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_risk CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_operations CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_openapi CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_catalog CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_promotion CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_experiment CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_advertising CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_supply_chain CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_finance CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_customer_service CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_forecasting CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_event_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_data_warehouse CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_intelligence CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_analytics CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_traffic CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_reliability CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_release CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_platform_ops CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS emall_routing CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- Local-only service-scoped migration principals mirror the production privilege boundary.
CREATE USER IF NOT EXISTS 'user_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_user.* TO 'user_migration'@'%';
CREATE USER IF NOT EXISTS 'product_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_product.* TO 'product_migration'@'%';
CREATE USER IF NOT EXISTS 'inventory_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_inventory.* TO 'inventory_migration'@'%';
CREATE USER IF NOT EXISTS 'order_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_order.* TO 'order_migration'@'%';
CREATE USER IF NOT EXISTS 'cart_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_cart.* TO 'cart_migration'@'%';
CREATE USER IF NOT EXISTS 'payment_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_payment.* TO 'payment_migration'@'%';
CREATE USER IF NOT EXISTS 'pricing_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_pricing.* TO 'pricing_migration'@'%';
CREATE USER IF NOT EXISTS 'marketing_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_marketing.* TO 'marketing_migration'@'%';
CREATE USER IF NOT EXISTS 'search_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_search.* TO 'search_migration'@'%';
CREATE USER IF NOT EXISTS 'fulfillment_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_fulfillment.* TO 'fulfillment_migration'@'%';
CREATE USER IF NOT EXISTS 'review_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_review.* TO 'review_migration'@'%';
CREATE USER IF NOT EXISTS 'after_sales_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_after_sales.* TO 'after_sales_migration'@'%';
CREATE USER IF NOT EXISTS 'merchant_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_merchant.* TO 'merchant_migration'@'%';
CREATE USER IF NOT EXISTS 'flash_sale_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_flash_sale.* TO 'flash_sale_migration'@'%';
CREATE USER IF NOT EXISTS 'recommendation_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_recommendation.* TO 'recommendation_migration'@'%';
CREATE USER IF NOT EXISTS 'cost_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_cost.* TO 'cost_migration'@'%';
CREATE USER IF NOT EXISTS 'identity_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_identity.* TO 'identity_migration'@'%';
CREATE USER IF NOT EXISTS 'risk_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_risk.* TO 'risk_migration'@'%';
CREATE USER IF NOT EXISTS 'operations_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_operations.* TO 'operations_migration'@'%';
CREATE USER IF NOT EXISTS 'openapi_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_openapi.* TO 'openapi_migration'@'%';
CREATE USER IF NOT EXISTS 'catalog_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_catalog.* TO 'catalog_migration'@'%';
CREATE USER IF NOT EXISTS 'promotion_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_promotion.* TO 'promotion_migration'@'%';
CREATE USER IF NOT EXISTS 'experiment_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_experiment.* TO 'experiment_migration'@'%';
CREATE USER IF NOT EXISTS 'advertising_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_advertising.* TO 'advertising_migration'@'%';
CREATE USER IF NOT EXISTS 'supply_chain_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_supply_chain.* TO 'supply_chain_migration'@'%';
CREATE USER IF NOT EXISTS 'finance_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_finance.* TO 'finance_migration'@'%';
CREATE USER IF NOT EXISTS 'customer_service_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_customer_service.* TO 'customer_service_migration'@'%';
CREATE USER IF NOT EXISTS 'forecasting_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_forecasting.* TO 'forecasting_migration'@'%';
CREATE USER IF NOT EXISTS 'event_platform_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_event_platform.* TO 'event_platform_migration'@'%';
CREATE USER IF NOT EXISTS 'data_warehouse_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_data_warehouse.* TO 'data_warehouse_migration'@'%';
CREATE USER IF NOT EXISTS 'intelligence_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_intelligence.* TO 'intelligence_migration'@'%';
CREATE USER IF NOT EXISTS 'analytics_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_analytics.* TO 'analytics_migration'@'%';
CREATE USER IF NOT EXISTS 'traffic_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_traffic.* TO 'traffic_migration'@'%';
CREATE USER IF NOT EXISTS 'reliability_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_reliability.* TO 'reliability_migration'@'%';
CREATE USER IF NOT EXISTS 'release_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_release.* TO 'release_migration'@'%';
CREATE USER IF NOT EXISTS 'platform_ops_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_platform_ops.* TO 'platform_ops_migration'@'%';
CREATE USER IF NOT EXISTS 'routing_migration'@'%' IDENTIFIED BY 'local-migration-only';
GRANT ALL PRIVILEGES ON emall_routing.* TO 'routing_migration'@'%';
