apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: emall-strict-mtls
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: emall-default-mtls
spec:
  host: "*.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-gateway-to-public-apis
spec:
  selector:
    matchLabels:
      app: gateway
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/emall/sa/gateway
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-checkout-service-calls
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/emall/sa/order
              - cluster.local/ns/emall/sa/payment
      to:
        - operation:
            ports:
              - "8083"
              - "8084"
              - "8087"
              - "8088"
