apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emall.fullname" . }}-runtime
  labels:
    {{- include "emall.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.global.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
