{{- if .Values.serviceDefaults.autoscaling.enabled }}
{{- range .Values.services }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "emall.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Release.Name }}-{{ .name }}
  minReplicas: {{ $.Values.serviceDefaults.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.serviceDefaults.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.serviceDefaults.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
