{{- if .Values.migration.enabled }}
{{- range .Values.services }}
{{- if ne .database false }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}-migration
  labels:
    {{- include "emall.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}-migration
automountServiceAccountToken: false
{{- end }}
{{- end }}
{{- end }}
