{{- if and .Values.migration.enabled .Values.migration.externalSecrets.enabled }}
{{- range .Values.services }}
{{- if ne .database false }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-migration
  labels:
    {{- include "emall.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}-migration
spec:
  refreshInterval: {{ $.Values.migration.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.migration.externalSecrets.storeKind }}
    name: {{ $.Values.migration.externalSecrets.storeName }}
  target:
    name: {{ .name }}-migration
    creationPolicy: Owner
  data:
    - secretKey: EMALL_MIGRATION_DB_USERNAME
      remoteRef:
        key: {{ $.Values.migration.externalSecrets.remoteKeyPrefix }}/{{ .name }}
        property: username
    - secretKey: EMALL_MIGRATION_DB_PASSWORD
      remoteRef:
        key: {{ $.Values.migration.externalSecrets.remoteKeyPrefix }}/{{ .name }}
        property: password
{{- end }}
{{- end }}
{{- end }}
