{{- range .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
    {{- include "emall.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
automountServiceAccountToken: false
{{- end }}
