{{- if not .Values.reports.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "emall-loadtest.reportClaim" . }}
  labels:
    app.kubernetes.io/name: emall-loadtest
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.reports.storageClass }}
  storageClassName: {{ .Values.reports.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.reports.size }}
{{- end }}
