ALTER TABLE inventory_item
    MODIFY COLUMN total BIGINT NOT NULL,
    MODIFY COLUMN reserved BIGINT NOT NULL,
    MODIFY COLUMN sold BIGINT NOT NULL;

ALTER TABLE inventory_bucket
    MODIFY COLUMN total BIGINT NOT NULL,
    MODIFY COLUMN reserved BIGINT NOT NULL,
    MODIFY COLUMN sold BIGINT NOT NULL;
