input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "platform" => "emall"
      "log_schema" => "application-json"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "emall-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
