global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
          - host.docker.internal:8081
          - host.docker.internal:8082
          - host.docker.internal:8083
          - host.docker.internal:8084
          - host.docker.internal:8085
          - host.docker.internal:8086
          - host.docker.internal:8087
          - host.docker.internal:8088
          - host.docker.internal:8089
          - host.docker.internal:8090
          - host.docker.internal:8091
          - host.docker.internal:8092
          - host.docker.internal:8093
          - host.docker.internal:8094
          - host.docker.internal:8095
          - host.docker.internal:8096
          - host.docker.internal:8097
          - host.docker.internal:8098
          - host.docker.internal:8099
          - host.docker.internal:8100
          - host.docker.internal:8101
          - host.docker.internal:8102
          - host.docker.internal:8103
          - host.docker.internal:8104
          - host.docker.internal:8105
          - host.docker.internal:8106
          - host.docker.internal:8107
          - host.docker.internal:8108
          - host.docker.internal:8109
          - host.docker.internal:8110
          - host.docker.internal:8111
          - host.docker.internal:8112
          - host.docker.internal:8113
          - host.docker.internal:8114
          - host.docker.internal:8115
          - host.docker.internal:8116
